volumes:
  mqdata:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker/musicbrainz/volumes/mqdata
      o: bind
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker/musicbrainz/volumes/pgdata
      o: bind
  solrdata:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker/musicbrainz/volumes/solrdata
      o: bind
  dbdump:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker/musicbrainz/volumes/dbdump
      o: bind
  solrdump:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker/musicbrainz/volumes/solrdump
      o: bind
