services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    environment:
      - ZO_DATA_DIR=/data
      - ZO_LOCAL_MODE=true
      - ZO_LOCAL_MODE_STORAGE=disk
      - ZO_WEB_URL=https://logs.ablz.au
      - ZO_GRPC_ADDR=0.0.0.0
      - ZO_GRPC_PORT=5081
    env_file:
      - ${XDG_RUNTIME_DIR}/secrets/openobserve-stack.env
    volumes:
      - ${DATA_ROOT}/openobserve:/data
    restart: unless-stopped
    ports:
      - "5080:5080"
      - "5081:5081"
