version: "3.3"
services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - "8083:8080"
    volumes:
      - ${DATA_ROOT}/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      # App uses relative paths from /app workdir - mount accordingly
      - ${DATA_ROOT}/StirlingPDF/extraConfigs:/app/configs
      - ${DATA_ROOT}/StirlingPDF/customFiles:/customFiles/
      - ${DATA_ROOT}/StirlingPDF/logs:/app/logs/
      - ${DATA_ROOT}/StirlingPDF/pipeline:/app/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
