---
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    restart: unless-stopped
    cap_add:
      - NET_RAW
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Perth
    volumes:
      - ${DATA_ROOT}/smokeping/config:/config
      - ${DATA_ROOT}/smokeping/data:/data
    ports:
      - 8084:80
