version: "3"
services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    labels:
      - io.containers.autoupdate=registry
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT}/tautulli/:/config
    environment:
      - TZ=Australia/Perth
    ports:
      - 8181:8181
