version: "3.5"
services:
  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:latest
    labels:
      - io.containers.autoupdate=registry
    command: server start
    volumes:
      - "${DATA_ROOT}/atuin/config:/config"
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      # Points to the 'postgresql' service defined below
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@postgresql/${ATUIN_DB_NAME}
      RUST_LOG: info,atuin_server=debug
    depends_on:
      - postgresql

  postgresql:
    image: docker.io/library/postgres:14
    labels:
      - io.containers.autoupdate=registry
    restart: unless-stopped
    volumes:
      - "${DATA_ROOT}/atuin/database:/var/lib/postgresql/data/:U"
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
