version: "3.8"

services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:1
    labels:
      - io.containers.autoupdate=registry
    container_name: uptime-kuma
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DATA_ROOT}/uptime-kuma:/app/data
      - /etc/localtime:/etc/localtime:ro
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
