---
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    labels:
      - io.containers.autoupdate=registry
    container_name: smokeping
    restart: unless-stopped
    environment:
      # Rootless podman: PUID=0 maps to host user
      - PUID=0
      - PGID=0
      - TZ=Australia/Perth
    volumes:
      - ${DATA_ROOT}/smokeping/config:/config
      - ${DATA_ROOT}/smokeping/data:/data
    ports:
      - 8084:80
